name: Build macOS .app

# Run on pushes to main, or manually via the UI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies & PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build .app
        run: |
          # replace main.py with your entrypoint or spec file
          pyinstaller --windowed --name BrainLinkCompanion --icon assets/favicon.ico BrainCompanion.py

      - name: Zip and upload artifact (using upload-artifact@v4)
        run: |
          cd dist
          zip -r BrainLinkCompanion.app.zip BrainLinkCompanion.app
        shell: bash

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist/BrainLinkCompanion.app.zip
