name: Build macOS .app

# Run on pushes to main, or manually via the UI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies & PyInstaller
        run: |
          python -m pip install --upgrade pip          
          pip install -r requirements_cross_platform.txt
          pip install pyinstaller

      - name: Build .app
        run: |
          pyinstaller BrainCompanion_macOS.spec

      - name: List dist directory contents
        run: |
          ls -l dist
        shell: bash

      - name: Zip and upload artifact (using upload-artifact@v4)
        run: |
          cd dist
          ls -l
          if [ -d "BrainCompanion.app" ]; then
            zip -r BrainCompanion.app.zip BrainCompanion.app
          else
            echo "BrainCompanion.app not found! Listing contents:" && ls -l && exit 1
          fi
        shell: bash

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist/BrainLinkCompanion.app.zip
