name: Build macOS .app

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies & PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_cross_platform.txt
          pip install pyinstaller

      - name: Build .app
        run: |
          pyinstaller BrainCompanion_macOS.spec

      - name: Inspect dist directory recursively
        run: |
          echo "::group::Dist contents"
          ls -lR dist
          echo "::endgroup::"
        shell: bash

      - name: Fix permissions & remove quarantine
        run: |
          chmod +x dist/BrainLinkCompanion.app/Contents/MacOS/BrainLinkCompanion
          xattr -dr com.apple.quarantine dist/BrainLinkCompanion.app
        shell: bash

      - name: Codesign app (ad-hoc)
        run: |
          codesign --force --deep --sign - dist/BrainLinkCompanion.app
        shell: bash

      - name: Package .app preserving metadata
        run: |
          cd dist
          if [ -d "BrainLinkCompanion.app" ]; then
            ditto -c -k --sequesterRsrc --keepParent \
              "BrainLinkCompanion.app" "macos-app-bundle.zip"
          else
            echo "ERROR: BrainLinkCompanion.app not found" && ls -l && exit 1
          fi
        shell: bash

      - name: Upload .app bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app-bundle
          path: dist/macos-app-bundle.zip

      - name: Upload raw Mach-O binary
        uses: actions/upload-artifact@v4
        with:
          name: macos-binary
          path: dist/BrainLinkCompanion.app/Contents/MacOS/BrainLinkCompanion
